### ISSUE TITLE
Cannot read property 'split' of undefined (getLocales)

### ISSUE THREAD

**Issue by lennertderyck** [digitalartlab/expo-plugin-localization#26]
I installed the package through the Expo CLI, added the needed plugin config and tried to use the `getLocales()` method but got the following error message:

```zsh
# index.js (4:40)
Error: Cannot find native module 'ExpoPluginLocalization', js engine: hermes
```

Am i doing something wrong? I tried running it with Expo Go, and as a local build.

**Comment by ThijmenDeValk** [comment]
Hi @lennertderyck! That's weird indeed. The plugin doesn't work with Expo Go, but the local build should've done the trick. Can you share a repo with a fresh install of Expo and this plugin, so I can take a peek at what's going wrong? Otherwise I'm stuck at "works on my machine", and that's not helpful for you :)

**Comment by ThijmenDeValk** [comment]
Hi @lennertderyck! Circling back because I ran into this for a project myself too. I'm assuming you're building locally (not through EAS) and have an `ios` folder in your project. You have to delete that and let Expo recreate it on your next build. Then the error should be resolved :)

**Comment by lennertderyck** [comment]
Good to know, thanks!
